---
- hosts: master
  become: true
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{apiserver_advertise_address}}" --apiserver-cert-extra-sans="{{apiserver_cert_extra_sans}}"  --pod-network-cidr=10.244.0.0/16  creates=/etc/kubernetes/controller-manager.conf 

  - name: Setup kubeconfig for user
    command: "{{ item }}"
    with_items:
     - mkdir -p $HOME/.kube
     - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

  - name: Install flannel pod network
    block:
      - name: Copy flannel conf
        template:
          src: kube-flannel.j2
          dest: /tmp/kube-flannel.yaml
      - name: Create network
        command: kubectl create -f /tmp/kube-flannel.yaml creates=/var/run/flannel/subnet.env

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="/tmp/join-command"
